# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('check-failed', 'Check failed'), ('expired', 'Expired'), ('soon-to-expire', 'Soon to expire'), ('good', "Look's good")], default='pending', max_length=255)),
                ('expiration_date', models.DateTimeField()),
                ('registrar', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('last_checked', models.DateTimeField()),
                ('response', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('auth_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.Source'),
        ),
    ]
