# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_auto_20160817_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='source',
        ),
        migrations.AddField(
            model_name='domain',
            name='sources',
            field=models.ManyToManyField(to='checker.Source'),
        ),
    ]
